public class Printing 
{
    public static void main(String[] args)
    {
        //int, doubles, boolean, string
       
        int myAge = 999; //int - integer : for hole numbers
        double price = 4.99; //for decimal numbers

        boolean isGood; // variable declaration
        isGood = false; //variable intiaalization

        String name = "Tram Vo"; //set name to "Tram Vo"
        System.out.print ("Hello my name is " + name);
    
    }
}
